/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as MeWatchlistRouteImport } from './routes/me.watchlist'
import { Route as MePaymentsRouteImport } from './routes/me.payments'
import { Route as MeOrdersRouteImport } from './routes/me.orders'
import { Route as MeNotificationsRouteImport } from './routes/me.notifications'
import { Route as MeBidsRouteImport } from './routes/me.bids'
import { Route as MeAddressesRouteImport } from './routes/me.addresses'
import { Route as LiveAuctionsIdRouteImport } from './routes/live-auctions.$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPayoutsRouteImport } from './routes/dashboard.payouts'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardListingsRouteImport } from './routes/dashboard.listings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuctionsUpcomingRouteImport } from './routes/auctions.upcoming'
import { Route as AuctionsLiveRouteImport } from './routes/auctions.live'
import { Route as AuctionsEndingSoonRouteImport } from './routes/auctions.ending-soon'
import { Route as AuctionsIdRouteImport } from './routes/auctions.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminAuthenticationRouteImport } from './routes/admin.authentication'
import { Route as AdminAuctionsRouteImport } from './routes/admin.auctions'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as DashboardCreateListingIndexRouteImport } from './routes/dashboard.create-listing.index'
import { Route as ShopCategorySlugRouteImport } from './routes/shop.category.$slug'
import { Route as ShopBrandSlugRouteImport } from './routes/shop.brand.$slug'
import { Route as DashboardCreateListingSlugRouteImport } from './routes/dashboard.create-listing.$slug'
import { Route as DashboardCreateListingSlugDetailsRouteImport } from './routes/dashboard.create-listing.$slug.details'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuctionsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopRoute,
} as any)
const MeWatchlistRoute = MeWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => MeRoute,
} as any)
const MePaymentsRoute = MePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => MeRoute,
} as any)
const MeOrdersRoute = MeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MeRoute,
} as any)
const MeNotificationsRoute = MeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MeRoute,
} as any)
const MeBidsRoute = MeBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => MeRoute,
} as any)
const MeAddressesRoute = MeAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => MeRoute,
} as any)
const LiveAuctionsIdRoute = LiveAuctionsIdRouteImport.update({
  id: '/live-auctions/$id',
  path: '/live-auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayoutsRoute = DashboardPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsRoute = DashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsUpcomingRoute = AuctionsUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionsLiveRoute = AuctionsLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionsEndingSoonRoute = AuctionsEndingSoonRouteImport.update({
  id: '/ending-soon',
  path: '/ending-soon',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuctionsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthenticationRoute = AdminAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardCreateListingIndexRoute =
  DashboardCreateListingIndexRouteImport.update({
    id: '/create-listing/',
    path: '/create-listing/',
    getParentRoute: () => DashboardRoute,
  } as any)
const ShopCategorySlugRoute = ShopCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBrandSlugRoute = ShopBrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const DashboardCreateListingSlugRoute =
  DashboardCreateListingSlugRouteImport.update({
    id: '/create-listing/$slug',
    path: '/create-listing/$slug',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCreateListingSlugDetailsRoute =
  DashboardCreateListingSlugDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => DashboardCreateListingSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auctions': typeof AuctionsRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/authentication': typeof AdminAuthenticationRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/ending-soon': typeof AuctionsEndingSoonRoute
  '/auctions/live': typeof AuctionsLiveRoute
  '/auctions/upcoming': typeof AuctionsUpcomingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/live-auctions/$id': typeof LiveAuctionsIdRoute
  '/me/addresses': typeof MeAddressesRoute
  '/me/bids': typeof MeBidsRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/orders': typeof MeOrdersRoute
  '/me/payments': typeof MePaymentsRoute
  '/me/watchlist': typeof MeWatchlistRoute
  '/shop/$id': typeof ShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/me/': typeof MeIndexRoute
  '/dashboard/create-listing/$slug': typeof DashboardCreateListingSlugRouteWithChildren
  '/shop/brand/$slug': typeof ShopBrandSlugRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/dashboard/create-listing/': typeof DashboardCreateListingIndexRoute
  '/dashboard/create-listing/$slug/details': typeof DashboardCreateListingSlugDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/authentication': typeof AdminAuthenticationRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/ending-soon': typeof AuctionsEndingSoonRoute
  '/auctions/live': typeof AuctionsLiveRoute
  '/auctions/upcoming': typeof AuctionsUpcomingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/live-auctions/$id': typeof LiveAuctionsIdRoute
  '/me/addresses': typeof MeAddressesRoute
  '/me/bids': typeof MeBidsRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/orders': typeof MeOrdersRoute
  '/me/payments': typeof MePaymentsRoute
  '/me/watchlist': typeof MeWatchlistRoute
  '/shop/$id': typeof ShopIdRoute
  '/admin': typeof AdminIndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/me': typeof MeIndexRoute
  '/dashboard/create-listing/$slug': typeof DashboardCreateListingSlugRouteWithChildren
  '/shop/brand/$slug': typeof ShopBrandSlugRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/dashboard/create-listing': typeof DashboardCreateListingIndexRoute
  '/dashboard/create-listing/$slug/details': typeof DashboardCreateListingSlugDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auctions': typeof AuctionsRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/authentication': typeof AdminAuthenticationRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/ending-soon': typeof AuctionsEndingSoonRoute
  '/auctions/live': typeof AuctionsLiveRoute
  '/auctions/upcoming': typeof AuctionsUpcomingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/live-auctions/$id': typeof LiveAuctionsIdRoute
  '/me/addresses': typeof MeAddressesRoute
  '/me/bids': typeof MeBidsRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/orders': typeof MeOrdersRoute
  '/me/payments': typeof MePaymentsRoute
  '/me/watchlist': typeof MeWatchlistRoute
  '/shop/$id': typeof ShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/me/': typeof MeIndexRoute
  '/dashboard/create-listing/$slug': typeof DashboardCreateListingSlugRouteWithChildren
  '/shop/brand/$slug': typeof ShopBrandSlugRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/dashboard/create-listing/': typeof DashboardCreateListingIndexRoute
  '/dashboard/create-listing/$slug/details': typeof DashboardCreateListingSlugDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auctions'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/me'
    | '/privacy'
    | '/returns'
    | '/sell'
    | '/seller'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/authentication'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/auctions/$id'
    | '/auctions/ending-soon'
    | '/auctions/live'
    | '/auctions/upcoming'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/signup'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/listings'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/live-auctions/$id'
    | '/me/addresses'
    | '/me/bids'
    | '/me/notifications'
    | '/me/orders'
    | '/me/payments'
    | '/me/watchlist'
    | '/shop/$id'
    | '/admin/'
    | '/auctions/'
    | '/dashboard/'
    | '/me/'
    | '/dashboard/create-listing/$slug'
    | '/shop/brand/$slug'
    | '/shop/category/$slug'
    | '/dashboard/create-listing/'
    | '/dashboard/create-listing/$slug/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/returns'
    | '/sell'
    | '/seller'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/authentication'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/auctions/$id'
    | '/auctions/ending-soon'
    | '/auctions/live'
    | '/auctions/upcoming'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/signup'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/listings'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/live-auctions/$id'
    | '/me/addresses'
    | '/me/bids'
    | '/me/notifications'
    | '/me/orders'
    | '/me/payments'
    | '/me/watchlist'
    | '/shop/$id'
    | '/admin'
    | '/auctions'
    | '/dashboard'
    | '/me'
    | '/dashboard/create-listing/$slug'
    | '/shop/brand/$slug'
    | '/shop/category/$slug'
    | '/dashboard/create-listing'
    | '/dashboard/create-listing/$slug/details'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auctions'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/me'
    | '/privacy'
    | '/returns'
    | '/sell'
    | '/seller'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/authentication'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/auctions/$id'
    | '/auctions/ending-soon'
    | '/auctions/live'
    | '/auctions/upcoming'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/signup'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/listings'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/live-auctions/$id'
    | '/me/addresses'
    | '/me/bids'
    | '/me/notifications'
    | '/me/orders'
    | '/me/payments'
    | '/me/watchlist'
    | '/shop/$id'
    | '/admin/'
    | '/auctions/'
    | '/dashboard/'
    | '/me/'
    | '/dashboard/create-listing/$slug'
    | '/shop/brand/$slug'
    | '/shop/category/$slug'
    | '/dashboard/create-listing/'
    | '/dashboard/create-listing/$slug/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuctionsRoute: typeof AuctionsRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SellRoute: typeof SellRoute
  SellerRoute: typeof SellerRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  LiveAuctionsIdRoute: typeof LiveAuctionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/me/watchlist': {
      id: '/me/watchlist'
      path: '/watchlist'
      fullPath: '/me/watchlist'
      preLoaderRoute: typeof MeWatchlistRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/payments': {
      id: '/me/payments'
      path: '/payments'
      fullPath: '/me/payments'
      preLoaderRoute: typeof MePaymentsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/orders': {
      id: '/me/orders'
      path: '/orders'
      fullPath: '/me/orders'
      preLoaderRoute: typeof MeOrdersRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/notifications': {
      id: '/me/notifications'
      path: '/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof MeNotificationsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/bids': {
      id: '/me/bids'
      path: '/bids'
      fullPath: '/me/bids'
      preLoaderRoute: typeof MeBidsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/addresses': {
      id: '/me/addresses'
      path: '/addresses'
      fullPath: '/me/addresses'
      preLoaderRoute: typeof MeAddressesRouteImport
      parentRoute: typeof MeRoute
    }
    '/live-auctions/$id': {
      id: '/live-auctions/$id'
      path: '/live-auctions/$id'
      fullPath: '/live-auctions/$id'
      preLoaderRoute: typeof LiveAuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payouts': {
      id: '/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof DashboardPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings': {
      id: '/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof DashboardListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/upcoming': {
      id: '/auctions/upcoming'
      path: '/upcoming'
      fullPath: '/auctions/upcoming'
      preLoaderRoute: typeof AuctionsUpcomingRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/live': {
      id: '/auctions/live'
      path: '/live'
      fullPath: '/auctions/live'
      preLoaderRoute: typeof AuctionsLiveRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/ending-soon': {
      id: '/auctions/ending-soon'
      path: '/ending-soon'
      fullPath: '/auctions/ending-soon'
      preLoaderRoute: typeof AuctionsEndingSoonRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authentication': {
      id: '/admin/authentication'
      path: '/authentication'
      fullPath: '/admin/authentication'
      preLoaderRoute: typeof AdminAuthenticationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/create-listing/': {
      id: '/dashboard/create-listing/'
      path: '/create-listing'
      fullPath: '/dashboard/create-listing/'
      preLoaderRoute: typeof DashboardCreateListingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/shop/category/$slug': {
      id: '/shop/category/$slug'
      path: '/category/$slug'
      fullPath: '/shop/category/$slug'
      preLoaderRoute: typeof ShopCategorySlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/brand/$slug': {
      id: '/shop/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/shop/brand/$slug'
      preLoaderRoute: typeof ShopBrandSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/dashboard/create-listing/$slug': {
      id: '/dashboard/create-listing/$slug'
      path: '/create-listing/$slug'
      fullPath: '/dashboard/create-listing/$slug'
      preLoaderRoute: typeof DashboardCreateListingSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-listing/$slug/details': {
      id: '/dashboard/create-listing/$slug/details'
      path: '/details'
      fullPath: '/dashboard/create-listing/$slug/details'
      preLoaderRoute: typeof DashboardCreateListingSlugDetailsRouteImport
      parentRoute: typeof DashboardCreateListingSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminAuthenticationRoute: typeof AdminAuthenticationRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminAuthenticationRoute: AdminAuthenticationRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuctionsRouteChildren {
  AuctionsIdRoute: typeof AuctionsIdRoute
  AuctionsEndingSoonRoute: typeof AuctionsEndingSoonRoute
  AuctionsLiveRoute: typeof AuctionsLiveRoute
  AuctionsUpcomingRoute: typeof AuctionsUpcomingRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

const AuctionsRouteChildren: AuctionsRouteChildren = {
  AuctionsIdRoute: AuctionsIdRoute,
  AuctionsEndingSoonRoute: AuctionsEndingSoonRoute,
  AuctionsLiveRoute: AuctionsLiveRoute,
  AuctionsUpcomingRoute: AuctionsUpcomingRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
}

const AuctionsRouteWithChildren = AuctionsRoute._addFileChildren(
  AuctionsRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface DashboardCreateListingSlugRouteChildren {
  DashboardCreateListingSlugDetailsRoute: typeof DashboardCreateListingSlugDetailsRoute
}

const DashboardCreateListingSlugRouteChildren: DashboardCreateListingSlugRouteChildren =
  {
    DashboardCreateListingSlugDetailsRoute:
      DashboardCreateListingSlugDetailsRoute,
  }

const DashboardCreateListingSlugRouteWithChildren =
  DashboardCreateListingSlugRoute._addFileChildren(
    DashboardCreateListingSlugRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardListingsRoute: typeof DashboardListingsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPayoutsRoute: typeof DashboardPayoutsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCreateListingSlugRoute: typeof DashboardCreateListingSlugRouteWithChildren
  DashboardCreateListingIndexRoute: typeof DashboardCreateListingIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardListingsRoute: DashboardListingsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPayoutsRoute: DashboardPayoutsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCreateListingSlugRoute: DashboardCreateListingSlugRouteWithChildren,
  DashboardCreateListingIndexRoute: DashboardCreateListingIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MeRouteChildren {
  MeAddressesRoute: typeof MeAddressesRoute
  MeBidsRoute: typeof MeBidsRoute
  MeNotificationsRoute: typeof MeNotificationsRoute
  MeOrdersRoute: typeof MeOrdersRoute
  MePaymentsRoute: typeof MePaymentsRoute
  MeWatchlistRoute: typeof MeWatchlistRoute
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeAddressesRoute: MeAddressesRoute,
  MeBidsRoute: MeBidsRoute,
  MeNotificationsRoute: MeNotificationsRoute,
  MeOrdersRoute: MeOrdersRoute,
  MePaymentsRoute: MePaymentsRoute,
  MeWatchlistRoute: MeWatchlistRoute,
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

interface ShopRouteChildren {
  ShopIdRoute: typeof ShopIdRoute
  ShopBrandSlugRoute: typeof ShopBrandSlugRoute
  ShopCategorySlugRoute: typeof ShopCategorySlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIdRoute: ShopIdRoute,
  ShopBrandSlugRoute: ShopBrandSlugRoute,
  ShopCategorySlugRoute: ShopCategorySlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuctionsRoute: AuctionsRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SellRoute: SellRoute,
  SellerRoute: SellerRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  LiveAuctionsIdRoute: LiveAuctionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
