/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as LiveAuctionsIdRouteImport } from './routes/live-auctions.$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPayoutsRouteImport } from './routes/dashboard.payouts'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardListingsRouteImport } from './routes/dashboard.listings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as DashboardCreateListingIndexRouteImport } from './routes/dashboard.create-listing.index'
import { Route as DashboardCreateListingSlugRouteImport } from './routes/dashboard.create-listing.$slug'
import { Route as DashboardCreateListingSlugDetailsRouteImport } from './routes/dashboard.create-listing.$slug.details'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopRoute,
} as any)
const LiveAuctionsIdRoute = LiveAuctionsIdRouteImport.update({
  id: '/live-auctions/$id',
  path: '/live-auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayoutsRoute = DashboardPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsRoute = DashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const DashboardCreateListingIndexRoute =
  DashboardCreateListingIndexRouteImport.update({
    id: '/create-listing/',
    path: '/create-listing/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCreateListingSlugRoute =
  DashboardCreateListingSlugRouteImport.update({
    id: '/create-listing/$slug',
    path: '/create-listing/$slug',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCreateListingSlugDetailsRoute =
  DashboardCreateListingSlugDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => DashboardCreateListingSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sell': typeof SellRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/live-auctions/$id': typeof LiveAuctionsIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/create-listing/$slug': typeof DashboardCreateListingSlugRouteWithChildren
  '/dashboard/create-listing/': typeof DashboardCreateListingIndexRoute
  '/dashboard/create-listing/$slug/details': typeof DashboardCreateListingSlugDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sell': typeof SellRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/live-auctions/$id': typeof LiveAuctionsIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/create-listing/$slug': typeof DashboardCreateListingSlugRouteWithChildren
  '/dashboard/create-listing': typeof DashboardCreateListingIndexRoute
  '/dashboard/create-listing/$slug/details': typeof DashboardCreateListingSlugDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sell': typeof SellRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/live-auctions/$id': typeof LiveAuctionsIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/create-listing/$slug': typeof DashboardCreateListingSlugRouteWithChildren
  '/dashboard/create-listing/': typeof DashboardCreateListingIndexRoute
  '/dashboard/create-listing/$slug/details': typeof DashboardCreateListingSlugDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/returns'
    | '/sell'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/listings'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/live-auctions/$id'
    | '/shop/$id'
    | '/dashboard/'
    | '/dashboard/create-listing/$slug'
    | '/dashboard/create-listing/'
    | '/dashboard/create-listing/$slug/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/returns'
    | '/sell'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/listings'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/live-auctions/$id'
    | '/shop/$id'
    | '/dashboard'
    | '/dashboard/create-listing/$slug'
    | '/dashboard/create-listing'
    | '/dashboard/create-listing/$slug/details'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/returns'
    | '/sell'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/listings'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/live-auctions/$id'
    | '/shop/$id'
    | '/dashboard/'
    | '/dashboard/create-listing/$slug'
    | '/dashboard/create-listing/'
    | '/dashboard/create-listing/$slug/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SellRoute: typeof SellRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  LiveAuctionsIdRoute: typeof LiveAuctionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/live-auctions/$id': {
      id: '/live-auctions/$id'
      path: '/live-auctions/$id'
      fullPath: '/live-auctions/$id'
      preLoaderRoute: typeof LiveAuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payouts': {
      id: '/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof DashboardPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings': {
      id: '/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof DashboardListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/dashboard/create-listing/': {
      id: '/dashboard/create-listing/'
      path: '/create-listing'
      fullPath: '/dashboard/create-listing/'
      preLoaderRoute: typeof DashboardCreateListingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-listing/$slug': {
      id: '/dashboard/create-listing/$slug'
      path: '/create-listing/$slug'
      fullPath: '/dashboard/create-listing/$slug'
      preLoaderRoute: typeof DashboardCreateListingSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-listing/$slug/details': {
      id: '/dashboard/create-listing/$slug/details'
      path: '/details'
      fullPath: '/dashboard/create-listing/$slug/details'
      preLoaderRoute: typeof DashboardCreateListingSlugDetailsRouteImport
      parentRoute: typeof DashboardCreateListingSlugRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface DashboardCreateListingSlugRouteChildren {
  DashboardCreateListingSlugDetailsRoute: typeof DashboardCreateListingSlugDetailsRoute
}

const DashboardCreateListingSlugRouteChildren: DashboardCreateListingSlugRouteChildren =
  {
    DashboardCreateListingSlugDetailsRoute:
      DashboardCreateListingSlugDetailsRoute,
  }

const DashboardCreateListingSlugRouteWithChildren =
  DashboardCreateListingSlugRoute._addFileChildren(
    DashboardCreateListingSlugRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardListingsRoute: typeof DashboardListingsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPayoutsRoute: typeof DashboardPayoutsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCreateListingSlugRoute: typeof DashboardCreateListingSlugRouteWithChildren
  DashboardCreateListingIndexRoute: typeof DashboardCreateListingIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardListingsRoute: DashboardListingsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPayoutsRoute: DashboardPayoutsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCreateListingSlugRoute: DashboardCreateListingSlugRouteWithChildren,
  DashboardCreateListingIndexRoute: DashboardCreateListingIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ShopRouteChildren {
  ShopIdRoute: typeof ShopIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIdRoute: ShopIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SellRoute: SellRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  LiveAuctionsIdRoute: LiveAuctionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
